predict:
  dir_folder: /Users/maksimfomin/IT/DS_practice/1.Регрессия/1.Realty_price_predict
  load:
    path:
      load: data
      write: data
  model_lr: LinearRegression
  path_model: model/model.pkl
  random_state: 10
  version_lr: 4
train:
  dir_folder: /Users/maksimfomin/IT/DS_practice/1.Регрессия/1.Realty_price_predict
  load:
    path:
      load: data
      write: data
  model_lr: LinearRegression
  name_experiment: experiment_rpp_2
  path_model: model/model.pkl
  random_state: 10
  test_size: 0.25
